import type { Config } from "tailwindcss";
const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        display: ["var(--font-display)"],
        sans:    ["var(--font-sans)"],
        mono:    ["var(--font-mono)"],
      },
      colors: {
        bg:      "#060608",
        surface: "#0e0e12",
        border:  "#1c1c24",
        accent:  "#00ff88",
        accent2: "#00c4ff",
        muted:   "#555566",
        gray: {
          800: "#1a1a1f",
          700: "#2a2a2f",
          600: "#3a3a3f",
          500: "#555566",
          400: "#777788",
          300: "#999999",
        },
      },
      transitionTimingFunction: {
        "ease-out": "cubic-bezier(0.23, 1, 0.32, 1)",
        "ease-in-out": "cubic-bezier(0.77, 0, 0.175, 1)",
        "ease-drawer": "cubic-bezier(0.32, 0.72, 0, 1)",
      },
      transitionDuration: {
        "100": "100ms",
        "150": "150ms",
        "200": "200ms",
        "300": "300ms",
        "400": "400ms",
        "500": "500ms",
      },
      keyframes: {
        "fade-up":    { "0%":{ opacity:"0", transform:"translateY(28px)" }, "100%":{ opacity:"1", transform:"translateY(0)" } },
        "fade-in":    { "0%":{ opacity:"0" }, "100%":{ opacity:"1" } },
        "pop-in":     { "0%":{ opacity:"0", transform:"scale(0.8)" }, "100%":{ opacity:"1", transform:"scale(1)" } },
        "scale-in":   { "0%":{ opacity:"0", transform:"scale(0.95)" }, "100%":{ opacity:"1", transform:"scale(1)" } },
        "slide-up":   { "0%":{ opacity:"0", transform:"translateY(16px)" }, "100%":{ opacity:"1", transform:"translateY(0)" } },
        "slide-down": { "0%":{ opacity:"0", transform:"translateY(-16px)" }, "100%":{ opacity:"1", transform:"translateY(0)" } },
        marquee:      { "0%":{ transform:"translateX(0)" }, "100%":{ transform:"translateX(-50%)" } },
        float:        { "0%,100%":{ transform:"translateY(0)" }, "50%":{ transform:"translateY(-10px)" } },
        "spin-slow":  { "0%":{ transform:"rotate(0deg)" }, "100%":{ transform:"rotate(360deg)" } },
        shimmer:      { "0%":{ backgroundPosition:"-200% center" }, "100%":{ backgroundPosition:"200% center" } },
        blink:        { "0%,100%":{ opacity:"1" }, "50%":{ opacity:"0" } },
        "scan":       { "0%":{ transform:"translateY(-100%)" }, "100%":{ transform:"translateY(400%)" } },
        glow:         { "0%,100%":{ opacity:"0.4" }, "50%":{ opacity:"1" } },
      },
      animation: {
        "fade-up":   "fade-up 0.7s ease forwards",
        "fade-in":   "fade-in 0.5s ease forwards",
        "pop-in":    "pop-in 0.4s cubic-bezier(0.23, 1, 0.32, 1) forwards",
        "scale-in":  "scale-in 0.3s cubic-bezier(0.23, 1, 0.32, 1) forwards",
        "slide-up":  "slide-up 0.4s cubic-bezier(0.23, 1, 0.32, 1) forwards",
        "slide-down": "slide-down 0.4s cubic-bezier(0.23, 1, 0.32, 1) forwards",
        marquee:     "marquee 32s linear infinite",
        float:       "float 4s ease-in-out infinite",
        "spin-slow": "spin-slow 20s linear infinite",
        shimmer:     "shimmer 3s linear infinite",
        blink:       "blink 1s step-end infinite",
        scan:        "scan 3s linear infinite",
        glow:        "glow 2.5s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
export default config;
